import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "./components/sidebar/Sidebar";
import GlobarStyleProvider from "./providers/GlobarSyleProvider";
import ContextProvider from "./providers/ContextProvider";
import { ClerkProvider } from "@clerk/nextjs";
import { auth } from "@clerk/nextjs/server";
import {Nunito} from 'next/font/google'
import NextTopLoader from "nextjs-toploader";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const nunito=Nunito({
  weight:['400', '500','600','700','800','900'],
  subsets:['latin'],
  
  
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;


}>) {
  const {userId}=auth()
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
            integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
            crossOrigin="anonymous"
            referrerPolicy="no-referrer"
          />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable}  ${nunito.className} antialiased` }
        >
          <NextTopLoader height={2} color="#27AE60" easing="cubic-bezier:0.53,0.21,0,1"/>
          <ContextProvider>
            <GlobarStyleProvider>
            {userId &&   <Sidebar />}
              {children}
            </GlobarStyleProvider>
          </ContextProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
